# 이것도 개발환경2

spring:
  application:
    name: KBoard

  # Thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:templates/views/

  # datasource 설정, 자바 명령을 시작하는 시점에서 받아옴
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${rds.username}
    password: ${rds.password}

  # security 설정 , oauth는 배포용 따로 만들어서 해보기
  security:
    oauth2:
      client:
        registration:
          google:   # registration 등록된 이름
            client-id: aaaa
            client-secret: aaaa
            scope:
              - email
              - profile
          facebook:
            client-id: bbbb
            client-secret: bbbb
            scope:  # 접근권한
              - email
              - public_profile
          naver:
            client-id: cccc
            client-secret: cccc
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code  # 코드 받고 인증하는 방식
            redirect-uri: cccc
        # provider 제공
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response   # scope 가 response 아래에 있음을 명시

  # MyBatis 매퍼(mapper) 파일 위치 설정
  # src/main/resources 이하의 경로 지정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml


app:
  #  페이징 관련 세팅값
  pagination:
    write_pages: 10  # 한 [페이징] 당 몇 개의 페이지를 표시?
    page_rows: 10   # 한 '페이지'에 몇 개의 글을 리스트화 표시?

  # 파일 업로드 경로
  upload:
    path: upload

  # OAuth2
  oauth2:

    password: 1234  #oauth2 인증한 회원에 대한 전용 패스워드, 보안주의!

    # Kakao 로그인 관련 세팅값
    kakao:
      client-id: dddd # REST Api 키
      redirect-uri: dddd # Redirect URI
      token-uri: https://kauth.kakao.com/oauth/token # access token 요청 URI
      user-info-uri: https://kapi.kakao.com/v2/user/me  # 사용자 profile 요청 URI
